### ISSUE TITLE
Keyboard not showing what I typed.

### ISSUE THREAD

**Issue by singhlovey** [evernote/evernote-sdk-php#21]
Hi,

I am facing an issue related to keyboard in evernote API. When evernote window open an I tried to enter email for authentication, It will not show what I typed and keyboard covers up all the UI box and I am not able to check what I typed there. I have gone through many links and other users also facing the same issue.

Please help and let me know how can this be fixed.

Thanks

**Comment by iafan** [comment]
How is this related to the PHP SDK? An additional information and screenshots of what you see on your screen might help better understand the problem.

**Comment by singhlovey** [comment]
@iafan 

You are correct. it is not related to SDK but I thought that I will get some solution from here.
 
Anyways, this is done. 

Thanks
